import { pgTable, text, integer, boolean, jsonb, timestamp } from 'drizzle-orm/pg-core';

export const activities = pgTable('activities', {
  id: text('id').primaryKey(),
  title: text('title').default(''),
  subtitle: text('subtitle').default(''),
  startDate: text('start_date').default(''),
  endDate: text('end_date').default(''),
  days: integer('days'),
  lineUrl: text('line_url').default('https://lin.ee/64ollTa'),
  lineGroupUrl: text('line_group_url'),
  fee: integer('fee').default(0),
  feeItems: jsonb('fee_items'),
  feeNote: text('fee_note'),
  leader: text('leader').default(''),
  maxParticipants: integer('max_participants').default(10),
  currentParticipants: integer('current_participants').default(0),
  meetingLocation: text('meeting_location').default(''),
  meetingTime: text('meeting_time').default(''),
  distanceKm: text('distance_km').default(''),
  elevationGain: text('elevation_gain').default(''),
  elevationLoss: text('elevation_loss').default(''),
  maxAltitude: text('max_altitude').default(''),
  videoUrl: text('video_url').default(''),
  coverImage: text('cover_image').default(''),
  difficulty: text('difficulty').default(''),
  status: text('status').default('recruiting'),
  isArchived: boolean('is_archived').default(false),
  archivedAt: text('archived_at'),
  description: text('description').default(''),
  gearNotice: text('gear_notice').default(''),
  itinerary: jsonb('itinerary'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});
